# Generated by Django 6.1 on 2026-08-22 22:55

import apps.accounts.managers
import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.TenantUserManager()),
                ("all_tenants", apps.accounts.managers.AllTenantsUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_staff",
            field=models.BooleanField(
                default=False,
                help_text="يفتح لوحة تحكم المنصة. ليس له أي معنى داخل سنتر.",
                verbose_name="من فريق المنصة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="فارغ = من فريق المنصة، خارج كل السناتر.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="150 حرفًا على الأكثر: حروف وأرقام و @ . + - _ فقط.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="اسم المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "username"], name="accounts_us_tenant__d92906_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("tenant", "username"), name="uq_username_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("username",),
                name="uq_platform_username",
            ),
        ),
    ]
