# Generated by Django 6.1 on 2026-08-22 22:21

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("slug", models.SlugField(max_length=40, unique=True, verbose_name="المعرّف")),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_public", models.BooleanField(default=True, verbose_name="متاح للعرض")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
                (
                    "max_students",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="حد الطلاب"),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حد المستخدمين"
                    ),
                ),
                (
                    "max_groups",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="حد المجموعات"),
                ),
                (
                    "max_cards",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="حد البطاقات"),
                ),
                (
                    "storage_mb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مساحة التخزين (ميجابايت)"
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="مدة الاحتفاظ بعد الأرشفة (يوم)"
                    ),
                ),
                (
                    "price_note",
                    models.CharField(blank=True, max_length=200, verbose_name="ملاحظة السعر"),
                ),
            ],
            options={
                "verbose_name": "باقة",
                "verbose_name_plural": "الباقات",
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[apps.tenancy.models.validate_slug],
                        verbose_name="المعرّف",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم السنتر")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=150, verbose_name="الاسم بالإنجليزية"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "تجريبي"),
                            ("ACTIVE", "نشط"),
                            ("PAST_DUE", "متأخر السداد"),
                            ("SUSPENDED", "موقوف"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        db_index=True,
                        default="TRIAL",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="نهاية التجربة"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="نهاية الاشتراك"
                    ),
                ),
                (
                    "grace_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="نهاية فترة السماح"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Cairo", max_length=50, verbose_name="المنطقة الزمنية"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ar", max_length=10, verbose_name="اللغة الافتراضية"),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, max_length=150, verbose_name="اسم المسؤول"),
                ),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="بريد المسؤول"),
                ),
                (
                    "owner_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="هاتف المسؤول"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات داخلية")),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التفعيل"),
                ),
                (
                    "suspended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الإيقاف"),
                ),
                ("suspended_reason", models.TextField(blank=True, verbose_name="سبب الإيقاف")),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الأرشفة"),
                ),
                (
                    "purge_after",
                    models.DateTimeField(blank=True, null=True, verbose_name="يُحذف نهائيًا بعد"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="tenancy.plan",
                        verbose_name="الباقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TENANT_CREATED", "إنشاء عميل"),
                            ("TENANT_UPDATED", "تعديل عميل"),
                            ("TENANT_SUSPENDED", "إيقاف عميل"),
                            ("TENANT_RESUMED", "إعادة تفعيل عميل"),
                            ("TENANT_ARCHIVED", "أرشفة عميل"),
                            ("TENANT_PURGED", "حذف بيانات عميل"),
                            ("TENANT_EXPORTED", "تصدير بيانات عميل"),
                            ("PLAN_CHANGED", "تغيير الباقة"),
                            ("FEATURE_CHANGED", "تغيير خاصية"),
                            ("LIMIT_CHANGED", "تغيير حد"),
                            ("DOMAIN_ADDED", "إضافة نطاق"),
                            ("DOMAIN_REMOVED", "حذف نطاق"),
                            ("IMPERSONATION_STARTED", "بدء الدخول نيابةً"),
                            ("IMPERSONATION_ENDED", "إنهاء الدخول نيابةً"),
                            ("SUBSCRIPTION_TRANSITION", "تغيير حالة الاشتراك"),
                        ],
                        max_length=40,
                        verbose_name="الإجراء",
                    ),
                ),
                ("object_repr", models.CharField(blank=True, max_length=200, verbose_name="الوصف")),
                ("changes", models.JSONField(blank=True, default=dict, verbose_name="التغييرات")),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="التاريخ")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_entries",
                        to="tenancy.tenant",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل المنصة",
                "verbose_name_plural": "سجلات المنصة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        db_index=True, max_length=253, unique=True, verbose_name="النطاق"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="النطاق الأساسي")),
                ("is_custom", models.BooleanField(default=False, verbose_name="نطاق خاص بالعميل")),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التحقق"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenancy.tenant",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "نطاق",
                "verbose_name_plural": "النطاقات",
                "ordering": ["-is_primary", "host"],
            },
        ),
        migrations.CreateModel(
            name="TenantFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        max_length=60,
                        validators=[apps.tenancy.models.validate_feature_key],
                        verbose_name="الخاصية",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("INHERIT", "حسب الباقة"), ("ON", "مُفعّل"), ("OFF", "مُعطّل")],
                        default="INHERIT",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="ملاحظة")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_overrides",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_feature_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "خاصية عميل",
                "verbose_name_plural": "خصائص العملاء",
                "ordering": ["tenant", "feature_key"],
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("students", models.PositiveIntegerField(default=0)),
                ("active_students", models.PositiveIntegerField(default=0)),
                ("users", models.PositiveIntegerField(default=0)),
                ("groups", models.PositiveIntegerField(default=0)),
                ("cards", models.PositiveIntegerField(default=0)),
                ("lessons_30d", models.PositiveIntegerField(default=0)),
                ("scans_30d", models.PositiveIntegerField(default=0)),
                (
                    "payments_30d_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("storage_mb", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "استخدام عميل",
                "verbose_name_plural": "استخدام العملاء",
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        max_length=60,
                        validators=[apps.tenancy.models.validate_feature_key],
                        verbose_name="الخاصية",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="tenancy.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "خاصية باقة",
                "verbose_name_plural": "خصائص الباقات",
                "ordering": ["plan", "feature_key"],
                "constraints": [
                    models.UniqueConstraint(fields=("plan", "feature_key"), name="uq_plan_feature")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["status", "expires_at"], name="tenancy_ten_status_d072d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformauditlog",
            index=models.Index(
                fields=["tenant", "-created_at"], name="tenancy_pla_tenant__c19b6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformauditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="tenancy_pla_actor_i_dacf5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformauditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="tenancy_pla_action_eb34e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformauditlog",
            index=models.Index(fields=["-created_at"], name="tenancy_pla_created_788ee0_idx"),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("tenant",),
                name="uq_one_primary_domain_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantfeature",
            constraint=models.UniqueConstraint(
                fields=("tenant", "feature_key"), name="uq_tenant_feature"
            ),
        ),
    ]
