# Generated by Django 6.1 on 2026-08-21 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="الاسم")),
                (
                    "name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="الكود")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
            ],
            options={
                "verbose_name": "مرحلة دراسية",
                "verbose_name_plural": "المراحل الدراسية",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="الاسم")),
                (
                    "name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="الكود")),
                ("color", models.CharField(default="#2b6cb0", max_length=7, verbose_name="اللون")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
            ],
            options={
                "verbose_name": "مادة",
                "verbose_name_plural": "المواد",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("code", models.CharField(max_length=20, unique=True, verbose_name="الكود")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="academics.educationalstage",
                        verbose_name="المرحلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف دراسي",
                "verbose_name_plural": "الصفوف الدراسية",
                "ordering": ["stage__order", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GradeSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "default_monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الرسوم الشهرية الافتراضية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="academics.grade",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="academics.subject",
                        verbose_name="المادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة لصف",
                "verbose_name_plural": "مواد الصفوف",
                "ordering": ["grade__order", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("code", models.CharField(max_length=30, unique=True, verbose_name="الكود")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="صفر = بلا حد", verbose_name="السعة"
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الرسوم الشهرية",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=9, verbose_name="العام الدراسي"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشطة"),
                            ("PAUSED", "متوقفة مؤقتًا"),
                            ("CLOSED", "مغلقة"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "default_late_after_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="حد التأخير (دقائق)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "grade_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="academics.gradesubject",
                        verbose_name="المادة/الصف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
                "ordering": ["grade_subject__grade__order", "grade_subject__subject__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "السبت"),
                            (1, "الأحد"),
                            (2, "الاثنين"),
                            (3, "الثلاثاء"),
                            (4, "الأربعاء"),
                            (5, "الخميس"),
                            (6, "الجمعة"),
                        ],
                        verbose_name="اليوم",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="من")),
                ("end_time", models.TimeField(verbose_name="إلى")),
                ("room", models.CharField(blank=True, max_length=30, verbose_name="القاعة")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academics.group",
                        verbose_name="المجموعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "موعد أسبوعي",
                "verbose_name_plural": "المواعيد الأسبوعية",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("full_name", models.CharField(max_length=150, verbose_name="الاسم")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="الهاتف")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب المستخدم",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="instructors",
                        to="academics.subject",
                        verbose_name="المواد",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرّس",
                "verbose_name_plural": "المدرّسون",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="academics.instructor",
                verbose_name="المدرّس",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["stage", "order"], name="academics_g_stage_i_f6cfee_idx"),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("stage", "name"), name="uq_grade_name_per_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupschedule",
            constraint=models.UniqueConstraint(
                fields=("group", "weekday", "start_time"), name="uq_schedule_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="ck_schedule_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="ck_schedule_weekday_range",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["grade_subject", "status"], name="academics_g_grade_s_83f905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["status"], name="academics_g_status_46ec5d_idx"),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("grade_subject", "name"), name="uq_group_name_per_offering"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_fee__gte", 0)), name="ck_group_fee_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="gradesubject",
            index=models.Index(fields=["subject", "grade"], name="academics_g_subject_ca8b38_idx"),
        ),
        migrations.AddConstraint(
            model_name="gradesubject",
            constraint=models.UniqueConstraint(
                fields=("grade", "subject"), name="uq_offering_grade_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradesubject",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_monthly_fee__gte", 0)),
                name="ck_offering_fee_non_negative",
            ),
        ),
    ]
