# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="grade",
            name="academics_g_stage_i_f6cfee_idx",
        ),
        migrations.RemoveIndex(
            model_name="gradesubject",
            name="academics_g_subject_ca8b38_idx",
        ),
        migrations.RemoveIndex(
            model_name="group",
            name="academics_g_grade_s_83f905_idx",
        ),
        migrations.RemoveIndex(
            model_name="group",
            name="academics_g_status_46ec5d_idx",
        ),
        migrations.AddField(
            model_name="educationalstage",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="gradesubject",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="groupschedule",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="educationalstage",
            name="code",
            field=models.CharField(db_index=True, max_length=20, verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="educationalstage",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="الاسم"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="code",
            field=models.CharField(db_index=True, max_length=20, verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="group",
            name="code",
            field=models.CharField(db_index=True, max_length=30, verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(db_index=True, max_length=20, verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="الاسم"),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["tenant", "stage", "order"], name="academics_g_tenant__8adeee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gradesubject",
            index=models.Index(
                fields=["tenant", "subject", "grade"], name="academics_g_tenant__e72b2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["tenant", "grade_subject", "status"], name="academics_g_tenant__329412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["tenant", "status"], name="academics_g_tenant__c9ff6b_idx"),
        ),
        migrations.AddConstraint(
            model_name="educationalstage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_stage_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="educationalstage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_stage_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_grade_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_group_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uq_subject_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_subject_code_per_tenant"
            ),
        ),
    ]
