# Generated by Django 6.1 on 2026-08-21 17:32

import apps.students.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "student_code",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="كود الطالب"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=150, verbose_name="الاسم الكامل"),
                ),
                (
                    "search_name",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=150),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.students.models.student_photo_path,
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "ذكر"), ("FEMALE", "أنثى")],
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="هاتف الطالب"
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=150, verbose_name="ولي الأمر"),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="هاتف ولي الأمر"
                    ),
                ),
                (
                    "guardian_relation",
                    models.CharField(
                        blank=True,
                        choices=[("FATHER", "الأب"), ("MOTHER", "الأم"), ("OTHER", "آخر")],
                        max_length=20,
                        verbose_name="صلة القرابة",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                ("school", models.CharField(blank=True, max_length=150, verbose_name="المدرسة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("SUSPENDED", "موقوف"),
                            ("TRANSFERRED", "منقول"),
                            ("GRADUATED", "متخرج"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "enrolled_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="تاريخ الالتحاق"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academics.grade",
                        verbose_name="الصف",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["status", "grade"], name="students_st_status_293aa0_idx"),
                    models.Index(fields=["full_name"], name="students_st_full_na_6ea9f7_idx"),
                    models.Index(fields=["search_name"], name="students_st_search__4c575a_idx"),
                    models.Index(fields=["guardian_phone"], name="students_st_guardia_c1bfb7_idx"),
                ],
            },
        ),
    ]
