# Generated by Django 6.1 on 2026-08-21 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("is_default", models.BooleanField(default=True, verbose_name="المجموعة الأساسية")),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="من"),
                ),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="إلى")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("ENDED", "منتهي"),
                            ("TRANSFERRED", "منقول"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GROUP_CHANGE", "تغيير مجموعة"),
                            ("LEFT_CENTER", "ترك السنتر"),
                            ("SCHEDULE", "تعارض مواعيد"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="سبب الإنهاء",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="academics.gradesubject",
                        verbose_name="المادة/الصف",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="academics.group",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك طالب بمجموعة",
                "verbose_name_plural": "اشتراكات الطلاب بالمجموعات",
                "ordering": ["-start_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"], name="students_st_student_d61bc1_idx"
                    ),
                    models.Index(fields=["group", "status"], name="students_st_group_i_da3413_idx"),
                    models.Index(
                        fields=["grade_subject", "status"], name="students_st_grade_s_49e84b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("student", "grade_subject"),
                        name="uq_active_assignment_per_offering",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="ck_assignment_date_order",
                    ),
                ],
            },
        ),
    ]
