# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_add_tenant"),
        ("students", "0002_studentgroupassignment"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_status_293aa0_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_full_na_6ea9f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_search__4c575a_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_guardia_c1bfb7_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentgroupassignment",
            name="students_st_student_d61bc1_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentgroupassignment",
            name="students_st_group_i_da3413_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentgroupassignment",
            name="students_st_grade_s_49e84b_idx",
        ),
        migrations.AddField(
            model_name="student",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="studentgroupassignment",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_code",
            field=models.CharField(db_index=True, max_length=20, verbose_name="كود الطالب"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "status", "grade"], name="students_st_tenant__8a5f84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "full_name"], name="students_st_tenant__af351e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "search_name"], name="students_st_tenant__1bc2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "guardian_phone"], name="students_st_tenant__f09f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgroupassignment",
            index=models.Index(
                fields=["tenant", "student", "status"], name="students_st_tenant__bc849b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgroupassignment",
            index=models.Index(
                fields=["tenant", "group", "status"], name="students_st_tenant__01f0dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgroupassignment",
            index=models.Index(
                fields=["tenant", "grade_subject", "status"], name="students_st_tenant__fdbb5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "student_code"), name="uq_student_code_per_tenant"
            ),
        ),
    ]
