# Generated by Django 6.1 on 2026-08-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.JSONField(verbose_name="القيمة")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setting_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عُدّل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد",
                "verbose_name_plural": "الإعدادات",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "إنشاء مستخدم"),
                            ("USER_UPDATED", "تعديل مستخدم"),
                            ("SETTING_CHANGED", "تغيير إعداد"),
                            ("STUDENT_CREATED", "إنشاء طالب"),
                            ("STUDENT_UPDATED", "تعديل طالب"),
                            ("STUDENT_STATUS_CHANGED", "تغيير حالة طالب"),
                            ("STUDENT_ASSIGNED", "إضافة طالب لمجموعة"),
                            ("STUDENT_UNASSIGNED", "إنهاء اشتراك طالب بمجموعة"),
                            ("STUDENT_TRANSFERRED", "نقل طالب بين المجموعات"),
                            ("CARD_IMPORTED", "استيراد بطاقات"),
                            ("CARD_ASSIGNED", "ربط بطاقة"),
                            ("CARD_RELEASED", "فك ربط بطاقة"),
                            ("CARD_MARKED_LOST", "الإبلاغ عن فقد بطاقة"),
                            ("CARD_DISABLED", "تعطيل بطاقة"),
                            ("CARD_REPLACED", "استبدال بطاقة"),
                            ("LESSON_CREATED", "إنشاء حصة"),
                            ("LESSON_UPDATED", "تعديل حصة"),
                            ("LESSON_OPENED", "فتح حصة"),
                            ("LESSON_COMPLETED", "إنهاء حصة"),
                            ("LESSON_CANCELLED", "إلغاء حصة"),
                            ("ATTENDANCE_CREATED", "تسجيل حضور"),
                            ("ATTENDANCE_MODIFIED", "تعديل حضور"),
                            ("ATTENDANCE_CANCELLED", "إلغاء حضور"),
                            ("ATTENDANCE_APPROVED", "اعتماد حضور استثنائي"),
                            ("CHARGE_CREATED", "إصدار رسوم"),
                            ("CHARGE_MODIFIED", "تعديل رسوم"),
                            ("CHARGE_WAIVED", "إعفاء من رسوم"),
                            ("CHARGE_CANCELLED", "إلغاء رسوم"),
                            ("PAYMENT_CREATED", "تحصيل دفعة"),
                            ("PAYMENT_REFUNDED", "استرداد دفعة"),
                        ],
                        max_length=60,
                        verbose_name="الإجراء",
                    ),
                ),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=200, verbose_name="الوصف")),
                ("changes", models.JSONField(blank=True, default=dict, verbose_name="التغييرات")),
                ("reason", models.TextField(blank=True, verbose_name="السبب")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="التاريخ")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="core_auditl_content_203ee2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="core_auditl_action_d80c2d_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="core_auditl_actor_i_502baf_idx"
                    ),
                    models.Index(fields=["-created_at"], name="core_auditl_created_1a76fa_idx"),
                ],
            },
        ),
    ]
