# Generated by Django 6.1 on 2026-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, verbose_name="المفتاح"
                    ),
                ),
                (
                    "next_value",
                    models.PositiveIntegerField(default=1, verbose_name="القيمة التالية"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "عدّاد",
                "verbose_name_plural": "العدّادات",
            },
        ),
    ]
