# Generated by Django 6.1 on 2026-08-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "إنشاء مستخدم"),
                    ("USER_UPDATED", "تعديل مستخدم"),
                    ("SETTING_CHANGED", "تغيير إعداد"),
                    ("STUDENT_CREATED", "إنشاء طالب"),
                    ("STUDENT_UPDATED", "تعديل طالب"),
                    ("STUDENT_STATUS_CHANGED", "تغيير حالة طالب"),
                    ("STUDENT_ASSIGNED", "إضافة طالب لمجموعة"),
                    ("STUDENT_UNASSIGNED", "إنهاء اشتراك طالب بمجموعة"),
                    ("STUDENT_TRANSFERRED", "نقل طالب بين المجموعات"),
                    ("CARD_IMPORTED", "استيراد بطاقات"),
                    ("CARD_ASSIGNED", "ربط بطاقة"),
                    ("CARD_RELEASED", "فك ربط بطاقة"),
                    ("CARD_MARKED_LOST", "الإبلاغ عن فقد بطاقة"),
                    ("CARD_DISABLED", "تعطيل بطاقة"),
                    ("CARD_REPLACED", "استبدال بطاقة"),
                    ("LESSON_CREATED", "إنشاء حصة"),
                    ("LESSON_UPDATED", "تعديل حصة"),
                    ("LESSON_OPENED", "فتح حصة"),
                    ("LESSON_COMPLETED", "إنهاء حصة"),
                    ("LESSON_CANCELLED", "إلغاء حصة"),
                    ("ATTENDANCE_CREATED", "تسجيل حضور"),
                    ("ATTENDANCE_MODIFIED", "تعديل حضور"),
                    ("ATTENDANCE_CANCELLED", "إلغاء حضور"),
                    ("ATTENDANCE_APPROVED", "اعتماد حضور استثنائي"),
                    ("CHARGE_CREATED", "إصدار رسوم"),
                    ("CHARGE_MODIFIED", "تعديل رسوم"),
                    ("CHARGE_WAIVED", "إعفاء من رسوم"),
                    ("CHARGE_CANCELLED", "إلغاء رسوم"),
                    ("PAYMENT_CREATED", "تحصيل دفعة"),
                    ("PAYMENT_REFUNDED", "استرداد دفعة"),
                    ("REPORT_EXPORTED", "تصدير تقرير"),
                ],
                max_length=60,
                verbose_name="الإجراء",
            ),
        ),
    ]
