# Generated by Django 6.1 on 2026-08-22 22:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_alter_auditlog_action"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_auditl_content_203ee2_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_auditl_action_d80c2d_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_auditl_actor_i_502baf_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_entries",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 8, 22, 22, 55, 50, 294251, tzinfo=datetime.timezone.utc
                ),
                verbose_name="أُنشئ في",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sequence",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 8, 22, 22, 55, 50, 294355, tzinfo=datetime.timezone.utc
                ),
                verbose_name="أُنشئ في",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="setting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="key",
            field=models.CharField(db_index=True, max_length=50, verbose_name="المفتاح"),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
        ),
        migrations.AlterField(
            model_name="setting",
            name="key",
            field=models.CharField(db_index=True, max_length=100, verbose_name="المفتاح"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "-created_at"], name="core_auditl_tenant__93f9ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "content_type", "object_id", "-created_at"],
                name="core_auditl_tenant__1f842b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "action", "-created_at"], name="core_auditl_tenant__76b1e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "actor", "-created_at"], name="core_auditl_tenant__b68267_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_sequence_key_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_setting_key_per_tenant"
            ),
        ),
    ]
