# Generated by Django 6.1 on 2026-08-21 18:58

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0002_studentgroupassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("billing_month", models.DateField(db_index=True, verbose_name="شهر الفوترة")),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المستحق",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="الخصم",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="المدفوع",
                    ),
                ),
                (
                    "balance",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("amount_due"), "-", models.F("discount_amount")
                            ),
                            "-",
                            models.F("total_paid"),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=10),
                        verbose_name="المتبقي",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "غير مسدد"),
                            ("PARTIALLY_PAID", "مسدد جزئيًا"),
                            ("PAID", "مسدد"),
                            ("OVERPAID", "سداد زائد"),
                            ("WAIVED", "معفى"),
                            ("CANCELLED", "ملغي"),
                        ],
                        db_index=True,
                        default="UNPAID",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="تاريخ الاستحقاق"),
                ),
                ("waived_reason", models.TextField(blank=True, verbose_name="سبب الإعفاء")),
                (
                    "generated_by",
                    models.CharField(
                        choices=[("AUTO", "تلقائي"), ("MANUAL", "يدوي")],
                        default="AUTO",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade_subject",
                    models.ForeignKey(
                        help_text="مرساة الفوترة — لا تتأثر بتغيير المجموعة",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="academics.gradesubject",
                        verbose_name="المادة/الصف",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="academics.group",
                        verbose_name="المجموعة وقت الإصدار",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "رسوم شهرية",
                "verbose_name_plural": "الرسوم الشهرية",
                "ordering": ["-billing_month", "student__full_name"],
                "permissions": [
                    ("waive_charge", "الإعفاء من الرسوم"),
                    ("generate_charges", "إصدار رسوم الشهر"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "kind",
                    models.CharField(
                        choices=[("PAYMENT", "تحصيل"), ("REFUND", "استرداد")],
                        default="PAYMENT",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="المبلغ"),
                ),
                ("paid_at", models.DateTimeField(db_index=True, verbose_name="التاريخ")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "نقدًا"),
                            ("BANK_TRANSFER", "تحويل بنكي"),
                            ("CARD", "بطاقة"),
                            ("WALLET", "محفظة إلكترونية"),
                            ("OTHER", "أخرى"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(max_length=30, unique=True, verbose_name="رقم الإيصال"),
                ),
                ("reference", models.CharField(blank=True, max_length=60, verbose_name="مرجع")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_collected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حصّلها",
                    ),
                ),
                (
                    "monthly_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.monthlycharge",
                        verbose_name="الرسوم",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="payments.payment",
                        verbose_name="يُلغي الدفعة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مالية",
                "verbose_name_plural": "الحركات المالية",
                "ordering": ["-paid_at", "-id"],
                "permissions": [("refund_payment", "استرداد دفعة")],
            },
        ),
        migrations.AddIndex(
            model_name="monthlycharge",
            index=models.Index(
                fields=["billing_month", "status"], name="payments_mo_billing_beb1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlycharge",
            index=models.Index(
                fields=["student", "-billing_month"], name="payments_mo_student_0d6ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlycharge",
            index=models.Index(
                condition=models.Q(("balance__gt", 0)),
                fields=["billing_month"],
                name="ix_charge_outstanding",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlycharge",
            index=models.Index(
                fields=["group", "billing_month"], name="payments_mo_group_i_6c87cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlycharge",
            constraint=models.UniqueConstraint(
                fields=("student", "grade_subject", "billing_month"), name="uq_charge_per_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_due__gte", 0), ("discount_amount__gte", 0), ("total_paid__gte", 0)
                ),
                name="ck_charge_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__lte", models.F("amount_due"))),
                name="ck_discount_not_exceeding_due",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "-paid_at"], name="payments_pa_student_2fb2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["monthly_charge", "paid_at"], name="payments_pa_monthly_51a7e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["paid_at", "method"], name="payments_pa_paid_at_cc2109_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["collected_by", "paid_at"], name="payments_pa_collect_45ced5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_payment_amount_positive"
            ),
        ),
    ]
