# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("students", "0003_add_tenant"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_student_2fb2e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_monthly_51a7e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_paid_at_cc2109_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_collect_45ced5_idx",
        ),
        migrations.AddField(
            model_name="monthlycharge",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(db_index=True, max_length=30, verbose_name="رقم الإيصال"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "student", "-paid_at"], name="payments_pa_tenant__17b583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "monthly_charge", "paid_at"],
                name="payments_pa_tenant__902a87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "paid_at", "method"], name="payments_pa_tenant__8bfc58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "collected_by", "paid_at"], name="payments_pa_tenant__16d2cb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "receipt_number"), name="uq_receipt_number_per_tenant"
            ),
        ),
    ]
