# Generated by Django 6.1 on 2026-08-21 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "card_number",
                    models.CharField(
                        db_index=True, max_length=30, unique=True, verbose_name="رقم البطاقة"
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="رمز QR"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "متاحة"),
                            ("ASSIGNED", "مخصصة"),
                            ("LOST", "مفقودة"),
                            ("DISABLED", "معطّلة"),
                            ("REPLACED", "مستبدلة"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, verbose_name="الدفعة"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ أول تخصيص"),
                ),
                (
                    "lost_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الفقد"),
                ),
                (
                    "disabled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ التعطيل"),
                ),
                (
                    "replaced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الاستبدال"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "current_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards_held",
                        to="students.student",
                        verbose_name="الطالب الحالي",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="cards.studentcard",
                        verbose_name="البطاقة البديلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بطاقة طالب",
                "verbose_name_plural": "بطاقات الطلاب",
                "ordering": ["card_number"],
            },
        ),
        migrations.CreateModel(
            name="CardAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                ("assigned_at", models.DateTimeField(verbose_name="من")),
                ("released_at", models.DateTimeField(blank=True, null=True, verbose_name="إلى")),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOST", "فقدان"),
                            ("DAMAGED", "تلف"),
                            ("REPLACED", "استبدال"),
                            ("GRADUATED", "تخرج/مغادرة"),
                            ("DISABLED", "تعطيل"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="سبب الإنهاء",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_assignments_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_history",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_history",
                        to="cards.studentcard",
                        verbose_name="البطاقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصيص بطاقة",
                "verbose_name_plural": "سجل تخصيص البطاقات",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="studentcard",
            index=models.Index(fields=["status", "batch"], name="cards_stude_status_00aeba_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ASSIGNED")),
                fields=("current_student",),
                name="uq_one_active_card_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("current_student__isnull", False), ("status", "ASSIGNED")),
                    models.Q(
                        models.Q(("status", "ASSIGNED"), _negated=True),
                        ("current_student__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_card_holder_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="cardassignment",
            index=models.Index(
                fields=["student", "-assigned_at"], name="cards_carda_student_eb30a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("card",),
                name="uq_open_assignment_per_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("student",),
                name="uq_open_assignment_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("released_at__isnull", True),
                    ("released_at__gte", models.F("assigned_at")),
                    _connector="OR",
                ),
                name="ck_card_assign_dates",
            ),
        ),
    ]
