# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("students", "0002_studentgroupassignment"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cardassignment",
            name="cards_carda_student_eb30a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentcard",
            name="cards_stude_status_00aeba_idx",
        ),
        migrations.AddField(
            model_name="cardassignment",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="studentcard",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="studentcard",
            name="card_number",
            field=models.CharField(db_index=True, max_length=30, verbose_name="رقم البطاقة"),
        ),
        migrations.AddIndex(
            model_name="cardassignment",
            index=models.Index(
                fields=["tenant", "student", "-assigned_at"], name="cards_carda_tenant__7823ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcard",
            index=models.Index(
                fields=["tenant", "status", "batch"], name="cards_stude_tenant__1e9326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcard",
            index=models.Index(
                fields=["tenant", "qr_token"], name="cards_stude_tenant__25f41a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcard",
            constraint=models.UniqueConstraint(
                fields=("tenant", "card_number"), name="uq_card_number_per_tenant"
            ),
        ),
    ]
