# Generated by Django 6.1 on 2026-08-21 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("cards", "0001_initial"),
        ("lessons", "0001_initial"),
        ("students", "0002_studentgroupassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ABSENT", "غائب"),
                            ("CHECKED_IN", "بالداخل"),
                            ("CHECKED_OUT", "انصرف"),
                            ("CANCELLED", "ملغي"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الوضع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "حاضر"),
                            ("LATE", "متأخر"),
                            ("ABSENT", "غائب"),
                            ("PARTIAL", "حضور جزئي"),
                            ("CANCELLED", "ملغي"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "عادي"),
                            ("ALTERNATIVE_GROUP", "مجموعة بديلة"),
                            ("MAKEUP", "تعويضية"),
                            ("MANUAL", "يدوي"),
                            ("EXCEPTIONAL", "استثنائي"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("check_in_at", models.DateTimeField(blank=True, null=True, verbose_name="الحضور")),
                (
                    "check_out_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="الانصراف"),
                ),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(default=0, verbose_name="دقائق التأخير"),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="المدة"),
                ),
                ("is_manual", models.BooleanField(default=False, verbose_name="تدخل يدوي")),
                (
                    "requires_approval",
                    models.BooleanField(default=False, verbose_name="يحتاج اعتمادًا"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_source",
                    models.CharField(
                        choices=[
                            ("HID", "قارئ باركود"),
                            ("CAMERA", "كاميرا"),
                            ("MANUAL", "يدوي"),
                            ("SYSTEM", "النظام"),
                        ],
                        default="HID",
                        max_length=20,
                        verbose_name="مصدر التسجيل",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_as_assigned",
                        to="academics.group",
                        verbose_name="مجموعته المعتادة",
                    ),
                ),
                (
                    "attended_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_as_attended",
                        to="academics.group",
                        verbose_name="المجموعة الحالية",
                    ),
                ),
                (
                    "card_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="cards.studentcard",
                        verbose_name="البطاقة المستخدمة",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_check_outs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="lessons.lesson",
                        verbose_name="الحصة",
                    ),
                ),
                (
                    "makeup_for_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeups",
                        to="lessons.lesson",
                        verbose_name="تعويض عن حصة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور",
                "verbose_name_plural": "سجلات الحضور",
                "ordering": ["-check_in_at", "-id"],
                "permissions": [
                    ("scan_any_group", "المسح لأي مجموعة"),
                    ("approve_exceptional", "اعتماد الحضور الاستثنائي"),
                    ("correct_attendance", "تصحيح الحضور يدويًا"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "تسجيل حضور"),
                            ("CHECK_OUT", "تسجيل انصراف"),
                            ("DUPLICATE", "مسح مكرر"),
                            ("DENIED", "مرفوض"),
                            ("MANUAL_EDIT", "تعديل يدوي"),
                            ("CANCEL", "إلغاء"),
                            ("APPROVAL", "اعتماد"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("result_code", models.CharField(db_index=True, max_length=40)),
                ("message", models.CharField(blank=True, max_length=200)),
                ("device_id", models.CharField(blank=True, db_index=True, max_length=60)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="cards.studentcard",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث مسح",
                "verbose_name_plural": "أحداث المسح",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["lesson", "state"], name="attendance__lesson__c11921_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "-check_in_at"], name="attendance__student_e4f031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["attended_group", "lesson"], name="attendance__attende_f312e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["-check_in_at"], name="ix_att_recent"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                condition=models.Q(("attendance_type", "NORMAL"), _negated=True),
                fields=["lesson", "attendance_type"],
                name="ix_att_alternative",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="uq_attendance_lesson_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("check_out_at__isnull", True),
                    ("check_out_at__gte", models.F("check_in_at")),
                    _connector="OR",
                ),
                name="ck_attendance_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("check_in_at__isnull", False), ("state__in", ["CHECKED_IN", "CHECKED_OUT"])
                    ),
                    ("state__in", ["ABSENT", "CANCELLED"]),
                    _connector="OR",
                ),
                name="ck_attendance_state_requires_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attendance_type", "MAKEUP"), _negated=True),
                    ("makeup_for_lesson__isnull", False),
                    _connector="OR",
                ),
                name="ck_makeup_requires_source_lesson",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["lesson", "-created_at"], name="attendance__lesson__aa2077_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["result_code", "-created_at"], name="attendance__result__b332b8_idx"
            ),
        ),
    ]
