# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_add_tenant"),
        ("attendance", "0001_initial"),
        ("cards", "0001_initial"),
        ("lessons", "0001_initial"),
        ("students", "0002_studentgroupassignment"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__lesson__c11921_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__student_e4f031_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__attende_f312e7_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="ix_att_recent",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="ix_att_alternative",
        ),
        migrations.RemoveIndex(
            model_name="attendanceevent",
            name="attendance__lesson__aa2077_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendanceevent",
            name="attendance__result__b332b8_idx",
        ),
        migrations.AddField(
            model_name="attendance",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="عُدّل في"),
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "lesson", "state"], name="attendance__tenant__d3e186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "student", "-check_in_at"], name="attendance__tenant__29d6b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "attended_group", "lesson"], name="attendance__tenant__d07319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["tenant", "-check_in_at"], name="ix_att_recent"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                condition=models.Q(("attendance_type", "NORMAL"), _negated=True),
                fields=["tenant", "lesson", "attendance_type"],
                name="ix_att_alternative",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["tenant", "lesson", "-created_at"], name="attendance__tenant__4eb4da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["tenant", "result_code", "-created_at"],
                name="attendance__tenant__f1946b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["tenant", "-created_at"], name="attendance__tenant__3bdc77_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("tenant", "idempotency_key"),
                name="uq_event_idempotency_per_tenant",
            ),
        ),
    ]
