# Generated by Django 6.1 on 2026-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحيات التقارير",
                "permissions": [
                    ("view_reports", "عرض التقارير"),
                    ("view_financial_reports", "عرض التقارير المالية"),
                    ("export_reports", "تصدير التقارير"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
