# Generated by Django 6.1 on 2026-08-21 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="عُدّل في")),
                (
                    "sequence_no",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="رقم الحصة"
                    ),
                ),
                ("lesson_date", models.DateField(db_index=True, verbose_name="التاريخ")),
                ("scheduled_start", models.DateTimeField(db_index=True, verbose_name="البداية")),
                ("scheduled_end", models.DateTimeField(verbose_name="النهاية")),
                ("check_in_opens_at", models.DateTimeField(verbose_name="فتح التسجيل")),
                ("check_in_closes_at", models.DateTimeField(verbose_name="إغلاق التسجيل")),
                ("late_after", models.DateTimeField(verbose_name="اعتبار التأخير بعد")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "مجدولة"),
                            ("OPEN", "جارية"),
                            ("COMPLETED", "منتهية"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "actual_start_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="الفتح الفعلي"),
                ),
                (
                    "actual_end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="الإنهاء الفعلي"),
                ),
                (
                    "expected_students",
                    models.PositiveSmallIntegerField(default=0, verbose_name="العدد المتوقع"),
                ),
                ("cancel_reason", models.TextField(blank=True, verbose_name="سبب الإلغاء")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="academics.group",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="academics.instructor",
                        verbose_name="المدرّس",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة",
                "verbose_name_plural": "الحصص",
                "ordering": ["-scheduled_start"],
                "permissions": [
                    ("open_lesson", "فتح الحصة"),
                    ("complete_lesson", "إنهاء الحصة"),
                    ("cancel_lesson", "إلغاء الحصة"),
                    ("generate_lessons", "توليد الحصص"),
                ],
                "indexes": [
                    models.Index(
                        fields=["group", "lesson_date"], name="lessons_les_group_i_2861ed_idx"
                    ),
                    models.Index(
                        fields=["status", "scheduled_start"], name="lessons_les_status_c83731_idx"
                    ),
                    models.Index(
                        fields=["lesson_date", "status"], name="lessons_les_lesson__8d2ae4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "scheduled_start"), name="uq_lesson_group_start"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scheduled_end__gt", models.F("scheduled_start"))),
                        name="ck_lesson_time_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("check_in_closes_at__gt", models.F("check_in_opens_at"))
                        ),
                        name="ck_lesson_window_order",
                    ),
                ],
            },
        ),
    ]
