# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_add_tenant"),
        ("lessons", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_group_i_2861ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_status_c83731_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="lessons_les_lesson__8d2ae4_idx",
        ),
        migrations.AddField(
            model_name="lesson",
            name="tenant",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tenancy.tenant",
                verbose_name="العميل",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["tenant", "group", "lesson_date"], name="lessons_les_tenant__db7084_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["tenant", "status", "scheduled_start"],
                name="lessons_les_tenant__0c056a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["tenant", "lesson_date", "status"], name="lessons_les_tenant__92d5e5_idx"
            ),
        ),
    ]
